version: '3.0'

services:
  druid:
    build:
      context: .
      dockerfile: Dockerfile_druid
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8090:8090"
  fili:
    build:
      context: .
      dockerfile: Dockerfile_fili
    ports:
      - "9998:9998"
    depends_on:
      - druid
