#!/bin/bash

travis/git_credentials.bash

#pick up the tags from the adjusted remote
git fetch --unshallow
git fetch --tags

echo $(git branch -v)

#get the last tag on this branch
LAST_TAG=$(git describe)
echo "INFO Last tag: $LAST_TAG"

#Build the new tag to push
NEW_TAG=$(LAST_TAG=${LAST_TAG} python travis/upversion.py)
echo "INFO Creating tag: $NEW_TAG"
git tag $NEW_TAG -a -m "Autogenerated version bump tag"

#push the new tag
echo "INFO Pushing tag"
git push origin $NEW_TAG


#Login to docker
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

#Build the dockerfile
docker build -t fili-wikipedia-example -f fili-wikipedia-example/Dockerfile .

#only push a successful build
DOCKER_BUILD_RETURN_CODE=$?
if [[ ${DOCKER_BUILD_RETURN_CODE} -ne 0 ]]; then
    echo "ERROR Docker build did not succeed."
    exit ${DOCKER_BUILD_RETURN_CODE}
fi

#tag and push the new build
REPO=fili/fili-wikipedia-example
docker tag fili-wikipedia-example $REPO:$NEW_TAG
docker push $REPO
